In [2]:
import pandas as pd

df_prices_ww = pd.read_parquet('prices_ww.parquet')
df_prices_ww

,stock_permalink,closing_price,high,stock_id,avg_short_volume,put_call_ratio,total_volume,sell_buy_ratio,date,market_cap_13f,total_shares,name,open,low,quarter_id,average_ranking,net_buys,held_by
0,aavl,10.00,10.0,173039,111110.0,0.009147,55649.0,NaN,2022-10-03,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.00,9.660,88,2942.0,-22.0,59
1,aavl,10.30,10.0,173039,34338.0,0.009147,19911.0,NaN,2022-10-04,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.00,10.000,88,2942.0,-22.0,59
2,aavl,10.10,10.0,173039,40076.0,0.009147,17821.0,NaN,2022-10-05,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.30,10.100,88,2942.0,-22.0,59
3,aavl,10.20,10.0,173039,61479.0,0.009147,22047.0,NaN,2022-10-06,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.10,9.900,88,2942.0,-22.0,59
4,aavl,9.75,10.0,173039,38977.0,0.009147,18316.0,NaN,2022-10-07,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.00,9.700,88,2942.0,-22.0,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369881,zyme,15.01,15.0,198839,22817.0,0.486631,242272.0,NaN,2025-02-14,972512978.0,66432117,ZYMEWORKS INC,14.73,14.610,96,1799.0,-3.0,171
369882,zyme,14.67,15.0,198839,51626.0,0.486631,295605.0,NaN,2025-02-18,972512978.0,66432117,ZYMEWORKS INC,15.00,14.453,96,1799.0,-3.0,171
369883,zyme,14.82,14.0,198839,66585.0,0.486631,275490.0,NaN,2025-02-19,972512978.0,66432117,ZYMEWORKS INC,14.63,14.500,96,1799.0,-3.0,171
369884,zyme,14.02,14.0,198839,55681.0,0.486631,468154.0,NaN,2025-02-20,972512978.0,66432117,ZYMEWORKS INC,14.72,13.890,96,1799.0,-3.0,171
369885,zyme,14.39,14.0,198839,56214.0,0.486631,342870.0,NaN,2025-02-21,972512978.0,66432117,ZYMEWORKS INC,14.19,13.850,96,1799.0,-3.0,171

In [3]:
df_prices_ww['closing_price'].describe()

count    361993.000000
mean        158.835082
std        7021.708143
min           0.000000
25%           3.640000
50%          11.250000
75%          35.825000
max      949200.000000
Name: closing_price, dtype: float64

In [4]:
df_prices_ww['closing_price'].isna().sum()

np.int64(7893)

In [5]:
mask = (df_prices_ww['closing_price'] == 0) | (df_prices_ww['closing_price'].isna())
print(f'удаляем 0 и nan из цен - {mask.sum()} значение ({mask.sum()/len(df_prices_ww) * 100:.2f}%)')
df_prices_ww = df_prices_ww[~mask].copy() # без .copy() pd кидает варнинги при редактировании
df_prices_ww.to_parquet('prices_ww_cleaned.parquet', index=False)
df_prices_ww

удаляем 0 и nan из цен - 8321 значение (2.25%)

,stock_permalink,closing_price,high,stock_id,avg_short_volume,put_call_ratio,total_volume,sell_buy_ratio,date,market_cap_13f,total_shares,name,open,low,quarter_id,average_ranking,net_buys,held_by
0,aavl,10.00,10.0,173039,111110.0,0.009147,55649.0,NaN,2022-10-03,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.00,9.660,88,2942.0,-22.0,59
1,aavl,10.30,10.0,173039,34338.0,0.009147,19911.0,NaN,2022-10-04,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.00,10.000,88,2942.0,-22.0,59
2,aavl,10.10,10.0,173039,40076.0,0.009147,17821.0,NaN,2022-10-05,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.30,10.100,88,2942.0,-22.0,59
3,aavl,10.20,10.0,173039,61479.0,0.009147,22047.0,NaN,2022-10-06,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.10,9.900,88,2942.0,-22.0,59
4,aavl,9.75,10.0,173039,38977.0,0.009147,18316.0,NaN,2022-10-07,33238852.0,5730320,AVALANCHE BIOTECHNOLOGIES INC,10.00,9.700,88,2942.0,-22.0,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369881,zyme,15.01,15.0,198839,22817.0,0.486631,242272.0,NaN,2025-02-14,972512978.0,66432117,ZYMEWORKS INC,14.73,14.610,96,1799.0,-3.0,171
369882,zyme,14.67,15.0,198839,51626.0,0.486631,295605.0,NaN,2025-02-18,972512978.0,66432117,ZYMEWORKS INC,15.00,14.453,96,1799.0,-3.0,171
369883,zyme,14.82,14.0,198839,66585.0,0.486631,275490.0,NaN,2025-02-19,972512978.0,66432117,ZYMEWORKS INC,14.63,14.500,96,1799.0,-3.0,171
369884,zyme,14.02,14.0,198839,55681.0,0.486631,468154.0,NaN,2025-02-20,972512978.0,66432117,ZYMEWORKS INC,14.72,13.890,96,1799.0,-3.0,171
369885,zyme,14.39,14.0,198839,56214.0,0.486631,342870.0,NaN,2025-02-21,972512978.0,66432117,ZYMEWORKS INC,14.19,13.850,96,1799.0,-3.0,171

In [6]:
# на всякий случай проверям тип
df_prices_ww['closing_price'].apply(lambda x: isinstance(x, float)).all()

np.True_

In [7]:
df_prices_ww['prev_date'] = df_prices_ww.groupby('stock_id')['date'].shift(1)
df_prices_ww['prev_closing_price'] = df_prices_ww.groupby('stock_id')['closing_price'].shift(1)
df_prices_ww['date_diff'] = (df_prices_ww['date'] - df_prices_ww['prev_date']).dt.days
df_prices_ww['price_change_perc'] = ((df_prices_ww['closing_price']/df_prices_ww['prev_closing_price']) * 100 - 100).round(2)
# -60 and 180 because 1:3 common split, 5 days is max holiday break
df_prices_ww['to_check'] = (df_prices_ww['date_diff'] > 5) | (df_prices_ww['price_change_perc'] < -60) | (df_prices_ww['price_change_perc'] > 180)

to_check = df_prices_ww[df_prices_ww['to_check']]['stock_id'].unique()

print(f'необходимо дополнительно проверить {df_prices_ww['to_check'].sum()} значений для {len(to_check)} акций - их соберем из второго источника данных')

import pickle
with open('to_check.pkl', 'wb') as file:
    pickle.dump(to_check, file)

необходимо дополнительно проверить 393 значений для 133 акций - их соберем из второго источника данных